### PR TITLE
Library, Step 1

### PR DESCRIPTION
**Pull request by Wohlstand**
This is a small commit where I fixed the QMake build on Windows.

As we discussed [here](https://github.com/Wohlstand/libADLMIDI/issues/254#issuecomment-1926364153), I will send you a sequence of pull-requests based on my `library-3` branch. I will send the next once you merge this. And then, continue this until all commits from the `library-3` will reach you.

### CODE REVIEW

**Comment by bisqwit** [comment]
What is the reason for changing from C++11 to C++17 in the commit?

**Comment by Wohlstand** [comment]
> What is the reason for changing from C++11 to C++17 in the commit?

I don't remind why I did that, but as I remind, I got some errors/warnings when I built this on Windows. I should try to check this again and tell what is a reason of this failure...

**Comment by Wohlstand** [comment]
Or wait... I remind that you specified in your Makefile the `c++1y`, and I though it was C++17, but it was actually C++14. But, I'll test the build on my end first, and then I'll tweak this case.

**Comment by Wohlstand** [comment]
Okay, I see, the C++17 is required because of the `std::string_veiw` being used by you in the code. With C++14 the build fails. The std::string_view is a part of C++17 standard: https://en.cppreference.com/w/cpp/header/string_view

**Review by bisqwit — APPROVED** [review]

**Pull request merged**
